---

- name: Copy redirect.conf
  become: true
ansible.builtin.template:
    src: redirect.conf.j2
    dest: "{{ mailcow__install_path }}/data/conf/nginx/redirect.conf"
    mode: "0540"
  when: mailcow__redirect_http_to_https

- name: Delete redirect.conf
  become: true
ansible.builtin.file:
    path: "{{ mailcow__install_path }}/data/conf/nginx/redirect.conf"
    state: absent
  when: not mailcow__redirect_http_to_https
