---

- name: Restart mailcow
  become: true
  shell: |
    {{ mailcow__compose_command }} --project-name {{ mailcow__docker_compose_project_name }} restart
  changed_when: false
  args:
    chdir: "{{ mailcow__install_path }}"

- name: Recreate mailcow
  become: true
  shell: |
    {{ mailcow__compose_command }} --project-name {{ mailcow__docker_compose_project_name }} down
    {{ mailcow__compose_command }} --project-name {{ mailcow__docker_compose_project_name }} up -d
  changed_when: false
  args:
    chdir: "{{ mailcow__install_path }}"

- name: Restart mailcow rspamd
  become: true
  shell: |
    {{ mailcow__compose_command }} --project-name {{ mailcow__docker_compose_project_name }} restart rspamd-mailcow
  changed_when: false
  args:
    chdir: "{{ mailcow__install_path }}"
